const constantCase = require('constant-case');
const camelCase = require('camel-case');

module.exports = ({ actions: { names, defaultNames, state } }) => {
  const actionNames = names || defaultNames;

  return `import { ${actionNames
    .map(constantCase)
    .join(', ')} } from '../../action-types';
import { ${actionNames.map(camelCase).join(', ')} } from '../';
${
    names
      ? ``
      : `
// 🔥 these action creator tests are generated by default, you want your own types here`
  }
describe('\`${state}\` action creators', () => {${actionNames
    .map(actionName => {
      const camelCasedName = camelCase(actionName);
      const constantCasedName = constantCase(actionName);
      return `
  it('should export \`${camelCasedName}\` function', () => {
    expect(${camelCasedName}).toBeDefined();
    expect(${camelCasedName}()).toEqual({
      type: ${constantCasedName}
    });
  });`;
    })
    .join('\n')}
});
`;
};
